### ISSUE TITLE
Writing for section #5 (Examples from hackathon)

### ISSUE THREAD

**Issue by lauterbur** [popsim-consortium/adding-species-manuscript#13]
Bos taurus @gregorgorjanc

**Comment by lauterbur** [comment]
Should we ditch the "demographic model that was added" section (I don't think there was one)?
And should we ditch the "species that was not added" section? I think the idea behind it (what species can be usefully modeled) will now be pretty well covered in the second half of section 3, "Making a popgen sim".

**Comment by gregorgorjanc** [comment]
Bos Taurus done in https://github.com/popsim-consortium/adding-species-manuscript/pull/25
