### ISSUE TITLE
Species/demographic scenarios added/worked on by community since original publication?

### ISSUE THREAD

**Issue by lauterbur** [popsim-consortium/adding-species-manuscript#14]
I know which ones were worked on during the hackathon, but not anything prior. I will trawl through the QC issues to find this, but if anyone has a list or remembers some off the top of their head, I'd appreciate the information.

**Comment by lauterbur** [comment]
Dropping link to relevant issue: https://github.com/popsim-consortium/stdpopsim/issues/1069

**Comment by gregorgorjanc** [comment]
BosTau is one!

**Comment by jeromekelleher** [comment]
Easiest to compare with the list in Table 1 in the [paper](https://elifesciences.org/articles/54967) I think.

I'm not sure which ones we're happy are fully QC'd, though.

**Comment by lauterbur** [comment]
Yeah, that's why I was asking the question about the catalog doc last week. Is everything in the catalog in the code fully QC'd? https://github.com/popsim-consortium/stdpopsim/tree/main/stdpopsim/catalog

**Comment by jeromekelleher** [comment]
It's a bit hazy I think. Some of the stuff in there originally was never properly QC'd, and there's definitely things in the module that are QC'd. I don't think the documentation bit was kept in sync.

**Comment by lauterbur** [comment]
@izabelcavassim since you started this very related issue https://github.com/popsim-consortium/stdpopsim/issues/1069 do you have any insight?

**Comment by lauterbur** [comment]
Here's a list of all of the species with QC issues and/or in the code base, I think this should represent all species worked on, whether or not they were added and QC'd. 

| Species | Issue | QC status | Merged | In catalog |
|------------|------------|------------|------------|------------|
| PanTro | https://github.com/popsim-consortium/stdpopsim/issues/1220 | not started | yes | no |
| HelAnn | https://github.com/popsim-consortium/stdpopsim/issues/1219 | not started | yes | no |
| PapAnu | https://github.com/popsim-consortium/stdpopsim/issues/1217 | not started | no | no |
| MyoLuc | https://github.com/popsim-consortium/stdpopsim/issues/899 | don't add | no | no |
| AnoCar | https://github.com/popsim-consortium/stdpopsim/issues/895 | finished | yes | no |
| ChlRei | https://github.com/popsim-consortium/stdpopsim/issues/890 | finished | yes | no |
| AedAeg | https://github.com/popsim-consortium/stdpopsim/issues/889 | finished | yes | no |
| AnaPla | https://github.com/popsim-consortium/stdpopsim/issues/888 | finished | yes | no |
| StrAga | https://github.com/popsim-consortium/stdpopsim/issues/881 | not finished | yes | no |
| HelMel | https://github.com/popsim-consortium/stdpopsim/issues/880 | not finished | yes | no |
| DroSec | https://github.com/popsim-consortium/stdpopsim/issues/873 | not finished | yes | no |
| AnoGam | https://github.com/popsim-consortium/stdpopsim/issues/859 | not finished | yes | no |
| BosTau |  https://github.com/popsim-consortium/stdpopsim/issues/559 | finished | yes | no |
| PonAbe | https://github.com/popsim-consortium/stdpopsim/issues/544 | not finished because liftover | yes | yes |
| HomSap | https://github.com/popsim-consortium/stdpopsim/issues/543 | not finished because liftover | yes | yes |
| EscCol | https://github.com/popsim-consortium/stdpopsim/issues/542 | finished | yes | yes |
| DroMel | https://github.com/popsim-consortium/stdpopsim/issues/541 | finished | yes | yes |
| CanFam | https://github.com/popsim-consortium/stdpopsim/issues/540 | finished | yes | yes |
| AraTha | https://github.com/popsim-consortium/stdpopsim/issues/539 | not finished because liftover | yes | yes |
| ApiMel | https://github.com/popsim-consortium/stdpopsim/pull/1025 | not started | yes | no |
| CaeEle | https://github.com/popsim-consortium/stdpopsim/issues/1226 | not started | yes | no |
| GasAcu | https://github.com/popsim-consortium/stdpopsim/issues/1091 | not started | yes | no |

The catalog needs updated - opened issue https://github.com/popsim-consortium/stdpopsim/issues/1230 for that.
