### ISSUE TITLE
Consolidate "population genomic models" vs "population genetic models"

### ISSUE THREAD

**Issue by gregorgorjanc** [popsim-consortium/adding-species-manuscript#24]
At the moment both phrases are used. Would be nice to pick one and stick with it. Either will work.

**Comment by gregorgorjanc** [comment]
Whole-genome simulations is another candidate to be brought to one fold

**Comment by lauterbur** [comment]
I don't have a strong preference on this, for now I'm going with "population genomic" just for consistency.

**Comment by gregorgorjanc** [comment]
I don't mind either, but would be good to be consistent throughout. We can do this at the end.
