### ISSUE TITLE
Specific writing and review tasks for paper

### ISSUE THREAD

**Issue by igronau** [popsim-consortium/adding-species-manuscript#47]
I'm listing some action items with suggestions of possible authors who could address them. Feel free to pass on to a more suitable author, or take on a different task.

**Section: Standardized genome-wide simulations**
- [x] review the 1st paragraph in this section, which was rewritten to provide a fundamental overview of popgen simulations. (@petrelharp , @lauterbur )
- [ ] check that the main arguments about whole-chromosome simulations are clearly covered in 4th paragraph (@andrewkern , @petrelharp )
- [x] elaborate on example of Hsieh, et al. in the 5th paragraph (@RyanGutenkunst )

**Section: Updates to stdpopsim and the species catalog**
- [x] summarize key updates in msprime v1.0 in 1-2 sentences (@jeromekelleher , @FranzBaumdicker)
- [x] summarize model of gene conversion in stdpopsim in 5-7 sentences (@FranzBaumdicker)
- [x] add 5-7 sentences on uploading annotations, DFEs and mention selection manuscript (@petrelharp , @andrewkern )
- [x] fill in the three missing numbers in 2nd paragraph: (@lauterbur )
        * number of intro to stdpopsim workshops
        * number of hackathon participants
        * number of species added *after* the hackathon (and not immediately after)
- [ ] update fig 1 using updated catalog and mark in diff color species added during the hackathon (@lauterbur )

**Section: Guidelines for implementing a population genomic simulation**
- [ ] overall review of this section, which was quite extensively edited in this round (@lauterbur , @DanSchrider, @petrelharp ) 
- [ ] do we want to explicitly specify the max number of scaffolds we allow in species added to the catalog? This is mentioned twice in this section: beginning and end (@petrelharp , @jeromekelleher )
- [ ] does stdpopsim strictly require us to provide a generation time in every species? (@jeromekelleher , @petrelharp )
- [x] review paragraph on modeling selection in simulations (@andrewkern )
- [x] add citation(s) about usefulness of realistic simulations of selection (@andrewkern , @BenHaller)
- [ ] add citation to selection paper (preprint?)
- [x] add citations to studies that infer DFEs (try to cover a few species) (@KirkLohmueller )
- [x] write short paragraphs on liftovers (@andrewkern )
- [x] figure out an appropriate citation for estimating $\theta$ from $\pi$ (currently, we're citing Tajima `89) ( @andrewkern  )
- [ ] remove or considerably clarify the table in the end of this section. Not sure it's necessary.

**Section: Examples of added species**
- [x] review description of mosquito model (@andrewkern  ) 
- [ ] maybe add table for chrom-specific parameters (similar to the one in [catalog](https://popsim-consortium.github.io/stdpopsim-docs/latest/catalog.html#sec_catalog_AnoGam_genome))
- [ ] maybe add figure of demographic model (similar to the one in [catalog](https://popsim-consortium.github.io/stdpopsim-docs/latest/_images/sec_catalog_anogam_models_gabonag1000g_1a17.png))
- [x] review edits made to the cattle example ( @gregorgorjanc  )

**Comment by andrewkern** [comment]
so there are a few places in the current draft were we are talking about selection/DFEs etc.. I think we should limit this or cut it out entirely for the present manuscript beyond something like "a forthcoming version update to stdpopsim will incorporate selection" 

I'll offer edits in my current pass along those lines.

**Comment by igronau** [comment]
We discussed this in one of the calls and said that we should give some details, but keep it minimal. For example, it might make sense to mention the ability to import notations from Ensembl and the use of DFEs. We can reconsider this approach, if people think it should all be left to the selection paper.

**Comment by lauterbur** [comment]
I think @petrelharp had some particular suggestions about how to approach it with the upcoming release, but I do recall the general consensus being that selection is very relevant and should be discussed to some extent. That's my feeling as well, at least with the paper as it currently is providing general simulation guidelines and guidance in addition to reporting on expanding the catalog.

**Comment by gregorgorjanc** [comment]
@igronau I am not sure how to tick of tasks in the above post, so I am writing here that I have completed `review edits made to the cattle example` in Andy's PR (since he did some editing of the section);)

**Comment by igronau** [comment]
Okay. I ticked that off. When I get time to review the updated version, I'll see what's left of this list after @andrewkern's pass.

**Comment by andrewkern** [comment]
my pass is sitting over at #49 waiting for review

**Comment by igronau** [comment]
I finally got some time to read through this. I approved the PR and wrote some comments. We can discuss them for the next pass

**Comment by igronau** [comment]
okay to merge, as far as I'm concerned

**Comment by jeromekelleher** [comment]
Looks like I've got the edit token, will make a pass through tomorrow.

**Comment by fbaumdicker** [comment]
I have written a short paragraph on the gene conversion feature in #57 .
