### ISSUE TITLE
Other reference for selfing?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/adding-species-manuscript#52]
The reference to Demes for selfing in the first intro paragraph is a bit weird:

> selfing (eg. as implemented in Demes(Gower, 2022)),

Do we have a reference for a paper that infers selfing as part of demography?

If not I'd suggest removing it.

**Comment by RyanGutenkunst** [comment]
We've got a paper that infers models with inbreeding for pumas and cabbage. They're not in catalog unfortunately, although maybe we should get one or both in there. https://doi.org/10.1093/molbev/msaa042

**Comment by jeromekelleher** [comment]
Sounds like the ideal reference.

**Comment by igronau** [comment]
The reference to Blischak et al. (2020) was added, so issue can be closed
