### ISSUE TITLE
Mention caveats with mixing parameter values from different sources/models

### ISSUE THREAD

**Issue by gregorgorjanc** [popsim-consortium/adding-species-manuscript#7]
Related to https://github.com/popsim-consortium/adding-species-manuscript/pull/6#discussion_r821783319 we should point out that often reported parameter values are tied to a model and its other parameters, so mixing values from different sources has its own caveats - I have been doing that when I had no other choice - its the best one can do when information is patchy.

**Comment by jeromekelleher** [comment]
Mutation rates are a good example of this and catch people out a lot I think. Worth mentinoing.

**Comment by lauterbur** [comment]
Added in section 3.

**Comment by gregorgorjanc** [comment]
I think this is mentioned well in the current draft, so will close this issue
