### ISSUE TITLE
add @nspope

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/adding-species-manuscript#73]
Nate has been doing a lot of work on releasing stdpopsim to go along with this paper - he needs to be a co-author!

**Comment by lauterbur** [comment]
Absolutely! We can add his info when Ilan compiles the edits.

**Comment by andrewkern** [comment]
+1

**Comment by igronau** [comment]
Okay. I will add Nate (Nethaniel Pope) in order (between Manolo Peres and Murillo Rodrigues), with the U Oregon affiliation. Let me know if that's okay.

**Comment by igronau** [comment]
I'm also noticing some author order issues. Within each category, we want authors to be ordered alphabetically, right?

**Comment by lauterbur** [comment]
That's what I remember, yes.

I know it's in the meeting notes somewhere, but the Slack search function is currently defeating me.

**Comment by igronau** [comment]
Seems like it. I did notice 2-3 inconsistencies with that rule. I'm switching them to be in their right location in alphabetical order and trying not to screw up the affiliations. It'll be a good idea to double check this after I make the PR

**Comment by andrewkern** [comment]
@igronau it's "Nathaniel S. Pope," (https://scholar.google.com/citations?user=XB1o3bEAAAAJ&hl=en) and yes the same affiliation as I have.

**Comment by igronau** [comment]
Got it. I'll push an update over the weekend. I'm still getting minor edits from authors and I'd like to take care of everything in one PR

**Comment by igronau** [comment]
Taken care of in my latest [PR](https://github.com/popsim-consortium/adding-species-manuscript/pull/75). This issue can be closed now.
