### ISSUE TITLE
whole-genome simulations

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/adding-species-manuscript#77]
The abstract touts stdpopsim as providing whole-genome simulations. This is also discussed at the end of the introduction, plus the section titled "the utility of \stdpopsim for genome-wide simulations". This gives the strong impression that stdpopsim does whole-genome simulations. A reader might then be somewhat surprised to then learn that they can only do single-chromosome simulations with stdpopsim!

**Comment by igronau** [comment]
I think that we're trying to avoid explicitly discussing the delta between whole-chrom simulations and whole-genome simulations. I guess we can/should be more careful about this distinction without having to add a detailed discussion about this issue. I think that some instances of 'whole-genome' could/should be replaced with 'whole-chromosome', and we can at least add one sentence saying that a major step in producing whole-genome simulation is enabling simulations of chromosome-length sequences.
@grahamgower - do you think it's also important to explicitly say what we're missing out by separately (and independently) modeling each chromosome?

**Comment by grahamgower** [comment]
I don't think it's necessary to discuss the distinction between whole-genome simulations and whole-chromosome simulations. But I do think it's important to not mislead the reader here.

**Comment by igronau** [comment]
Okay. I think that the correct balance should treat whole-genome simulations as the ultimate goal of stdpopsim, but not say that it currently achieves this. When we explicitly discuss what stdpopsim provides, we should use 'whole-chromosome' instead of 'whole-genome'. I'll scan the manuscript and make these adjustments.

**Comment by igronau** [comment]
I address this in PR #79. I basically left only two mentions of "whole-genome simulations": one in the abstract and one in the beginning of the discussion. The context there is the ultimate objective of stdpopsim, so I think that in this context it make sense. I replaced all other instances with "chromosome-scale simulations", which appears to be the more appropriate term. This includes a switch in the title of the section following the introduction.

I think that this is a good move, but I'm a bit afraid that a casual reader might find "chromosome-scale" too technical, while "whole-genome" is a more familiar term (even if not fully accurate). So I'm interested in what other think about this switch. @lauterbur, @jeromekelleher, @petrelharp , @andrewkern?

**Comment by lauterbur** [comment]
I'm fine with it either way.

**Comment by petrelharp** [comment]
This sounds good to me (I don't mind "chromosome-scale".)

**Comment by jeromekelleher** [comment]
Chromosome-scale is a good phrase I think, and I agree "whole-genome" would be misleading.
