### ISSUE TITLE
MSMC/IBDNe perform best with realistic recombination rates?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/adding-species-manuscript#97]
I was confused by this statement in the manuscript:
https://github.com/popsim-consortium/adding-species-manuscript/blob/95cf1d95b9222aa68f12d0f42c6994d753e79b34/adding_species_manuscript.tex#L348-L350

Those are methods to infer demographic histories directly from empirical data. In what sense do they work best with realistic recombination rates?

PS: PSMC/MSMC work pretty well even on quite short scaffolds.
https://www.biorxiv.org/content/10.1101/382036v1

**Comment by igronau** [comment]
These methods can produce reasonable estimate from shorter contigs and rough approximations of the recombination rates. However, in principle, they perform best when applied to long contigs (several Mbs) and when assuming realistic approximations of recombination rates. Admittedly, we're not having a subtle discussion here about the reliance of these methods on long sequences and realistic recombination rates. We're just trying to argue for the utility of chromosome-scale simulations.
